name: Fetch Res

on:
  workflow_dispatch: ~

jobs:
  Fetch-Wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install uv
          uv sync --all-extras

      - name: Restore Old Files
        run: |
          mkdir -p data/raw
          mkdir -p tmp
          wget -q ${{ secrets.PUBLIC_URL }} -O genshin.zip
          unzip -q genshin.zip -d data/raw
          rm -rf genshin.zip

      - name: Fetch Remote Files
        run: |
          uv run _main.py

      - name: Zip Data
        run: |
          cd data/raw
          zip -q -r genshin.zip *
          mv genshin.zip ../../tmp/genshin.zip
          cd ../..

      - name: sync s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'data'
          DEST_DIR: 'data'

      - name: sync r2
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          AWS_S3_BUCKET: ${{ secrets.R2_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_REGION: 'auto'
          SOURCE_DIR: 'tmp'
